// Register the service worker for the PWA demo
export const registerServiceWorker = async (): Promise<ServiceWorkerRegistration | null> => {
  if ('serviceWorker' in navigator) {
    try {
      // Use the service worker file that's generated by Vite PWA plugin
      const registration = await navigator.serviceWorker.register('/sw.js', {
        scope: '/',
        type: 'module',
      });
      
      console.log('Service Worker registered with scope:', registration.scope);
      return registration;
    } catch (error) {
      console.error('Service Worker registration failed:', error);
      return null;
    }
  }
  console.warn('Service workers are not supported in this browser');
  return null;
};
